# Generated by Django 4.1.5 on 2023-01-25 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entrance', models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 25, 22, 49, 41, 572675), verbose_name='Дата поступления')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(blank=True, verbose_name='Примерный возраст')),
                ('avatar', models.ImageField(upload_to='animal_account', verbose_name='Аватарка')),
                ('short_description', models.CharField(max_length=70, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('taken_home', models.DateTimeField(blank=True, null=True, verbose_name='Забрали домой')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.typeofanimal', verbose_name='Вид животного')),
            ],
        ),
    ]
