# Generated by Django 4.1.5 on 2023-01-25 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_entrance',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 25, 22, 54, 13, 414983), verbose_name='Дата поступления'),
        ),
    ]
