# Generated by Django 4.1.5 on 2023-01-25 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='short_description',
            field=models.CharField(default=datetime.datetime(2023, 1, 25, 22, 7, 1, 897289), max_length=70, verbose_name='Краткое описание'),
        ),
    ]
