# Generated by Django 4.1.5 on 2023-01-25 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_animal_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_entrance',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 25, 22, 7, 57, 349362), verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='short_description',
            field=models.CharField(max_length=70, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='taken_home',
            field=models.DateTimeField(default=None, verbose_name='Забрали домой'),
        ),
    ]
