# Generated by Django 4.1.5 on 2023-02-08 15:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_animal_date_entrance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="date_entrance",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2023, 2, 8, 18, 52, 32, 4065),
                verbose_name="Дата поступления",
            ),
        ),
    ]
