# Generated by Django 4.1.5 on 2023-02-20 18:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_animal_date_entrance"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="date_entrance",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2023, 2, 20, 21, 18, 49, 791324),
                verbose_name="Дата поступления",
            ),
        ),
    ]
