# Generated by Django 4.1.5 on 2023-01-25 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_animal_date_entrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_entrance',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 25, 22, 8, 33, 918638), verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='taken_home',
            field=models.DateTimeField(blank=True, verbose_name='Забрали домой'),
        ),
    ]
