# Generated by Django 4.1.5 on 2023-02-21 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_animal_is_active_alter_animal_date_entrance"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeofanimal",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="date_entrance",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2023, 2, 21, 21, 36, 54, 398273),
                verbose_name="Дата поступления",
            ),
        ),
    ]
