# Generated by Django 4.1.5 on 2023-02-22 15:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_animal_date_entrance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="date_entrance",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2023, 2, 22, 18, 35, 36, 943418),
                verbose_name="Дата поступления",
            ),
        ),
    ]
