# Generated by Django 4.1.5 on 2023-01-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Возраст"),
        ),
    ]
