# Generated by Django 4.1.5 on 2023-02-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Заблокировани/не заблокировани"
            ),
        ),
    ]
