# Generated by Django 4.1.5 on 2023-03-19 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activate_key",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Ключ активации"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="activation_key_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 21, 11, 57, 51, 296170, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Актуальность ключа",
            ),
        ),
    ]
