# Generated by Django 4.1.5 on 2023-03-19 12:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0005_user_activate_key_user_activation_key_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expired",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 21, 12, 2, 53, 741618, tzinfo=datetime.timezone.utc),
                verbose_name="Актуальность ключа",
            ),
        ),
    ]
